server:
  port: 8001
  servlet:
    context-path: /feihudui
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://118.89.248.60:13306/feihudui?characterEncoding=utf-8&useSSL=false
accesskey:
    accessKeyId: LTAIxr5jsBw2iqBP
    accessKeySecret: 1BsJEgK0KlrKL4RjoOEbnIRcIpJKLI
template:
    templateCode: SMS_139460231
    signName: 孙穆涛
img:
    location: images/
